version: "3"

services:
    frontend:
        build: ./frontend
        env_file:
            - .env
        ports:
            - "8080:8080"
        volumes:
            - "./frontend:/app/frontend"
        tty: true
        environment:
            TZ: Asia/Tokyo
        command: yarn run start
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./frontend/dist:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/log:/var/log/nginx
    backend:
        build: ./backend
        env_file:
            - .env
        ports:
            - "5000:${API_PORT:-5000}"
        volumes:
            - "./backend:/app/backend"
        tty: true
        environment:
            TZ: Asia/Tokyo
        command: flask run -h 0.0.0.0
    database:
        build: ./mysql
        platform: linux/x86_64
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            # - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - ./mysql/sqls:/docker-entrypoint-initdb.d
        environment:
            TZ: Asia/Tokyo
