version: "3"

services:
    backend:
        build: ./backend
        env_file:
            - .env.test
        ports:
            - "5000:${API_PORT:-5000}"
        volumes:
            - "./backend:/app/backend"
        tty: true
        environment:
            TZ: Asia/Tokyo
        depends_on:
            - database
        command: ../bin/wait-for-it.sh database:3306 --timeout=30 --strict -- flask run --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-5000}
    database:
        build: ./mysql
        platform: linux/x86_64
        env_file:
            - .env.test
        ports:
            - "3306:3306"
        volumes:
            # - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - ./mysql/sqls:/docker-entrypoint-initdb.d
        environment:
            TZ: Asia/Tokyo
    wait:
        image: willwill/wait-for-it:latest
