name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: create .env
        run: cp .env.sample .env
      - name: build docker container
        run: make build
      - name: start application on docker
        run: make start
      - name: run test
        run: make test
